services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-stayconnect_dev}
      POSTGRES_USER: ${DB_USER:-stayconnect_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stayconnect_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER:-stayconnect_user} -d ${DB_DATABASE:-stayconnect_dev}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # AdonisJS Application
  adonis_app:
    image: ghcr.io/macojaune/stay-connect:latest
    environment:
      NODE_ENV: production
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5433}
      DB_USER: ${DB_USER:-stayconnect_user}
      DB_PASSWORD: ${DB_PASSWORD:-stayconnect_password}
      DB_DATABASE: ${DB_DATABASE:-stayconnect_db}
      APP_KEY: ${APP_KEY:-your-32-character-secret-key-here}
      SESSION_DRIVER: cookie
      BREVO_API_KEY: ${BREVO_API_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      QUEUE_ENABLED: 'false'
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    # volumes:
    #   - ./uploads:/home/bun/app/uploads
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: none
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3333/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Database Admin (optional)
  adminer:
    image: adminer:latest
    ports:
      - '8088:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE:-stayconnect_db}
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
