services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AdonisJS Application
  adonis_app:
    image: ghcr.io/macojaune/stay-connect:develop
    secrets:
      - source: stayconnect_env_develop
        target: /app/.env
    environment:
      NODE_ENV: production
      QUEUE_ENABLED: "true"
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379
    ports:
      - "3334:3333"
    depends_on:
      - postgres
      - redis
    volumes:
      - /home/ubuntu/stayConnect/uploads:/app/uploads
    deploy:
      update_config:
        order: start-first
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--no-verbose",
    #       "--tries=1",
    #       "--spider",
    #       "http://127.0.0.1:3333/health",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 40s
  # Redis Queue Broker
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    ports:
      - "6378:6379"

  # Queue Worker
  queue_worker:
    image: ghcr.io/macojaune/stay-connect:develop
    secrets:
      - source: stayconnect_env_develop
        target: /app/.env
    environment:
      NODE_ENV: production
      QUEUE_ENABLED: "true"
      QUEUE_REDIS_HOST: redis
      QUEUE_REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres
    volumes:
      - /home/ubuntu/stayConnect/uploads:/app/uploads
    command: ["node", "bin/console.js", "queue:listen"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  # Development Database Admin (optional)
  adminer:
    image: adminer:latest
    ports:
      - "8089:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
secrets:
  stayconnect_env_develop:
    external: true
