onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  msgpackr-extract: true
