"""Generate the newsletter's print-style masthead and tile. Requires Pillow."""
from pathlib import Path
from math import hypot, sin
import re
from PIL import Image, ImageDraw, ImageFont, PngImagePlugin
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'public/email/weekly'
OUT.mkdir(parents=True, exist_ok=True)
S = 2
ORANGE = re.search(r"BRAND_PRIMARY_COLOR = '(#[0-9A-Fa-f]{6})'", (ROOT/'app/constants/branding.ts').read_text()).group(1)
INK = '#17131b'
CREAM = '#fff8e9'
meta = PngImagePlugin.PngInfo()
meta.add_text('Source', 'Original geometric halftone and typography by StayConnect. Generated by resources/email-assets/generate_weekly_art.py. Anton font: Google Fonts, SIL OFL.')
art = Image.new('RGB', (1280*S, 620*S), ORANGE)
d = ImageDraw.Draw(art)
# A circular screenprint field evokes a speaker cone. No photograph is simulated.
for y in range(-24, 680, 18):
    for x in range(320, 1400, 18):
        distance = hypot(x-1060, y-240)
        intensity = max(0, 1-distance/620)
        ring = (sin(distance/42)+1)/2
        radius = (1.3 + 6.8*intensity*(.35+.65*ring))
        d.ellipse(((x-radius)*S,(y-radius)*S,(x+radius)*S,(y+radius)*S),fill=INK)
font = ImageFont.truetype(str(ROOT/'resources/email-assets/Anton-Regular.ttf'), 196*S)
for text,x,y in [('LES SORTIES',55,75),('DE LA SEMAINE',115,330)]:
    box=d.textbbox((0,0),text,font=font)
    w,h=box[2]-box[0],box[3]-box[1]
    d.rectangle((x*S-18*S,y*S-16*S,x*S+w+24*S,y*S+h+19*S),fill=CREAM)
    d.text((x*S-box[0],y*S-box[1]),text,font=font,fill=INK)
art.resize((1280,620),Image.Resampling.LANCZOS).save(OUT/'masthead-v3.png',optimize=True,pnginfo=meta)
tile=Image.new('RGB',(48*S,48*S),ORANGE)
t=ImageDraw.Draw(tile)
for x in (12,36):
 for y in (12,36):
  t.ellipse(((x-1.5)*S,(y-1.5)*S,(x+1.5)*S,(y+1.5)*S),fill='#d34300')
tile.resize((48,48),Image.Resampling.LANCZOS).save(OUT/'dots-orange-v3.png',optimize=True,pnginfo=meta)
print('Newsletter art generated:',[(p.name,p.stat().st_size) for p in OUT.glob('*.png')])
